//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirsoftApp.Models.ModeloSql
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class airSoftAppEntities : DbContext
    {
        public airSoftAppEntities()
            : base("name=airSoftAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_COMUNA> TB_COMUNA { get; set; }
        public virtual DbSet<TB_ESCUADRON> TB_ESCUADRON { get; set; }
        public virtual DbSet<TB_INTEGRANTE> TB_INTEGRANTE { get; set; }
        public virtual DbSet<TB_JUEGO> TB_JUEGO { get; set; }
        public virtual DbSet<TB_MODO_JUEGO> TB_MODO_JUEGO { get; set; }
        public virtual DbSet<TB_PAGINA> TB_PAGINA { get; set; }
        public virtual DbSet<TB_PARTICIPA_JUEGO> TB_PARTICIPA_JUEGO { get; set; }
        public virtual DbSet<TB_PERSONA> TB_PERSONA { get; set; }
        public virtual DbSet<TB_POSICION> TB_POSICION { get; set; }
        public virtual DbSet<TB_RANGO> TB_RANGO { get; set; }
        public virtual DbSet<TB_REGION> TB_REGION { get; set; }
        public virtual DbSet<TB_SELECCION> TB_SELECCION { get; set; }
        public virtual DbSet<TB_TIPO_JUEGO> TB_TIPO_JUEGO { get; set; }
        public virtual DbSet<TB_TIPO_PARTIDA> TB_TIPO_PARTIDA { get; set; }
        public virtual DbSet<TB_TIPO_USUARIO> TB_TIPO_USUARIO { get; set; }
    }
}
