//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirsoftApp.Models.ModeloSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ESTADISTICA
    {
        public int IDMES { get; set; }
        public string DESCMES { get; set; }
        public Nullable<int> PERPORMES { get; set; }
        public Nullable<int> ESCUADRONPORMES { get; set; }
    }
}
