//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirsoftApp.Models.ModeloSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PERSONA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PERSONA()
        {
            this.TB_INTEGRANTE = new HashSet<TB_INTEGRANTE>();
            this.TB_JUEGO = new HashSet<TB_JUEGO>();
            this.TB_PARTICIPA_JUEGO = new HashSet<TB_PARTICIPA_JUEGO>();
            this.TB_SELECCION = new HashSet<TB_SELECCION>();
        }
    
        public int IDPERSONA { get; set; }
        public Nullable<long> RUTPERSONA { get; set; }
        public Nullable<int> IDUSUARIO { get; set; }
        public string DVPER { get; set; }
        public Nullable<int> IDCOMUNA { get; set; }
        public Nullable<int> IDRANGO { get; set; }
        public string NICKPERSONA { get; set; }
        public string NOMPERSONA { get; set; }
        public string APATERNOPER { get; set; }
        public string AMATERNOPER { get; set; }
        public string TELPERSONA { get; set; }
        public string CORREOPER { get; set; }
        public byte[] PERFILPERSONA { get; set; }
        public Nullable<int> EXPERIENCIAPER { get; set; }
    
        public virtual TB_COMUNA TB_COMUNA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_INTEGRANTE> TB_INTEGRANTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_JUEGO> TB_JUEGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PARTICIPA_JUEGO> TB_PARTICIPA_JUEGO { get; set; }
        public virtual TB_RANGO TB_RANGO { get; set; }
        public virtual TB_TIPO_USUARIO TB_TIPO_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SELECCION> TB_SELECCION { get; set; }
    }
}
