//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirsoftApp.Models.ModeloSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PAGINA
    {
        public int IDPAGINA { get; set; }
        public Nullable<int> IDUSUARIO { get; set; }
        public string DESCPAGINA { get; set; }
    
        public virtual TB_TIPO_USUARIO TB_TIPO_USUARIO { get; set; }
    }
}
