//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirsoftApp.Models.ModeloSql
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SELECCION
    {
        public int IDSELECCION { get; set; }
        public Nullable<int> IDPOSICION { get; set; }
        public Nullable<int> IDPERSONA { get; set; }
        public Nullable<bool> VALSELECCION { get; set; }
    
        public virtual TB_PERSONA TB_PERSONA { get; set; }
        public virtual TB_POSICION TB_POSICION { get; set; }
    }
}
